// Aquí van todas las recetas, organizadas por categoría.
// Para agregar una receta nueva, copia un bloque { ... } dentro del arreglo
// y cambia los datos. El "id" debe ser único en todo el archivo.
// dificultad: "fácil" | "media" | "difícil"
// dieta: "estándar" | "vegetariana" | "alta en proteína"
// calorias: valor aproximado por porción

const recetas = [
  {
    id: 1,
    nombre: "Arroz con pollo",
    categoria: "tradicional",
    tiempo: 40,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["arroz", "pollo", "cebolla", "ajo", "zanahoria"],
    pasos: ["Sofreír el pollo en un poco de aceite.", "Agregar la cebolla y el ajo picados.", "Agregar el arroz y el agua, dejar cocinar 20 minutos."],
  },
  {
    id: 2,
    nombre: "Sopa de verduras",
    categoria: "tradicional",
    tiempo: 30,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "vegetariana",
    ingredientes: ["papa", "zanahoria", "cebolla", "apio", "caldo de verduras"],
    pasos: ["Picar todas las verduras.", "Sofreír la cebolla y el apio.", "Agregar el resto de verduras y el caldo, cocinar 20 minutos."],
  },
  {
    id: 3,
    nombre: "Frijoles con garra",
    categoria: "tradicional",
    tiempo: 90,
    porciones: 6,
    dificultad: "difícil",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["frijol rojo", "garra de cerdo", "plátano", "cebolla", "ajo"],
    pasos: ["Remojar los frijoles la noche anterior.", "Cocinar los frijoles con la garra hasta ablandar.", "Agregar el plátano y sofrito de cebolla y ajo."],
  },
  {
    id: 4,
    nombre: "Sancocho de gallina",
    categoria: "tradicional",
    tiempo: 90,
    porciones: 6,
    dificultad: "difícil",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["gallina", "papa", "yuca", "plátano", "mazorca", "cilantro"],
    pasos: ["Cocinar la gallina en agua con sal.", "Agregar la papa, la yuca y el plátano.", "Agregar la mazorca y cocinar 20 minutos más, servir con cilantro."],
  },
  {
    id: 5,
    nombre: "Lentejas guisadas",
    categoria: "tradicional",
    tiempo: 45,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "vegetariana",
    ingredientes: ["lentejas", "tomate", "cebolla", "zanahoria", "comino"],
    pasos: ["Sofreír la cebolla y el tomate picados.", "Agregar las lentejas y cubrir con agua.", "Cocinar a fuego medio 30 minutos, agregar la zanahoria a mitad de cocción."],
  },
  {
    id: 6,
    nombre: "Bandeja paisa",
    categoria: "tradicional",
    tiempo: 60,
    porciones: 2,
    dificultad: "media",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["frijoles", "arroz", "carne molida", "chicharrón", "huevo", "plátano maduro"],
    pasos: ["Preparar los frijoles y el arroz por separado.", "Freír la carne, el chicharrón y el plátano maduro.", "Servir todo junto con un huevo frito encima."],
  },
  {
    id: 7,
    nombre: "Ajiaco santafereño",
    categoria: "tradicional",
    tiempo: 75,
    porciones: 4,
    dificultad: "difícil",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["pollo", "papa criolla", "papa pastusa", "mazorca", "guascas"],
    pasos: ["Cocinar el pollo con las papas hasta que se deshagan un poco.", "Agregar la mazorca y las guascas.", "Servir con crema de leche y alcaparras."],
  },
  {
    id: 8,
    nombre: "Tamales",
    categoria: "tradicional",
    tiempo: 120,
    porciones: 8,
    dificultad: "difícil",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["masa de maíz", "cerdo", "pollo", "zanahoria", "arveja", "hoja de plátano"],
    pasos: ["Preparar la masa con el caldo de las carnes.", "Armar los tamales sobre la hoja de plátano con masa, carne y verduras.", "Envolver y cocinar al vapor por 1 hora y media."],
  },
  {
    id: 9,
    nombre: "Mondongo",
    categoria: "tradicional",
    tiempo: 100,
    porciones: 6,
    dificultad: "difícil",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["mondongo", "papa", "zanahoria", "cebolla", "cilantro"],
    pasos: ["Cocinar el mondongo hasta que esté blando.", "Agregar la papa y la zanahoria en cubos.", "Sazonar y cocinar 20 minutos más, servir con cilantro."],
  },
  {
    id: 10,
    nombre: "Cazuela de mariscos",
    categoria: "tradicional",
    tiempo: 50,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["camarón", "calamar", "pescado", "leche de coco", "cilantro"],
    pasos: ["Sofreír un guiso de cebolla y tomate.", "Agregar los mariscos y cocinar unos minutos.", "Agregar la leche de coco y cocinar a fuego bajo 15 minutos."],
  },
  {
    id: 11,
    nombre: "Empanadas de carne",
    categoria: "tradicional",
    tiempo: 60,
    porciones: 10,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["masa de maíz", "carne molida", "papa", "cebolla", "comino"],
    pasos: ["Preparar el relleno de carne con papa y cebolla.", "Rellenar los discos de masa y cerrar bien.", "Freír en aceite caliente hasta dorar."],
  },
  {
    id: 12,
    nombre: "Pozole",
    categoria: "tradicional",
    tiempo: 90,
    porciones: 6,
    dificultad: "difícil",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["maíz pozolero", "cerdo", "chile", "cebolla", "orégano"],
    pasos: ["Cocinar el cerdo con el maíz pozolero hasta ablandar.", "Agregar el chile y sazonar.", "Servir con cebolla y orégano al gusto."],
  },
  {
    id: 13,
    nombre: "Caldo de costilla",
    categoria: "tradicional",
    tiempo: 60,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["costilla de res", "papa", "cilantro", "cebolla larga"],
    pasos: ["Cocinar la costilla en agua con sal hasta ablandar.", "Agregar la papa en trozos.", "Servir caliente con cilantro y cebolla picada."],
  },
  {
    id: 14,
    nombre: "Chuleta valluna",
    categoria: "tradicional",
    tiempo: 35,
    porciones: 2,
    dificultad: "media",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["chuleta de cerdo", "huevo", "pan rallado", "limón"],
    pasos: ["Aplanar la chuleta y sazonar con limón.", "Pasar por huevo batido y pan rallado.", "Freír hasta dorar por ambos lados."],
  },
  {
    id: 15,
    nombre: "Rondón costeño",
    categoria: "tradicional",
    tiempo: 80,
    porciones: 5,
    dificultad: "difícil",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["pescado", "yuca", "plátano", "leche de coco", "camarón"],
    pasos: ["Cocinar la yuca y el plátano en la leche de coco.", "Agregar el pescado y el camarón.", "Cocinar a fuego bajo 20 minutos más."],
  },
  {
    id: 16,
    nombre: "Pastel de papa y carne",
    categoria: "tradicional",
    tiempo: 55,
    porciones: 6,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["papa", "carne molida", "huevo", "queso", "cebolla"],
    pasos: ["Cocinar y triturar la papa hasta hacer puré.", "Preparar el relleno de carne con cebolla.", "Armar capas de puré y carne, hornear con queso encima."],
  },
  {
    id: 17,
    nombre: "Chicharrones con arepa",
    categoria: "tradicional",
    tiempo: 25,
    porciones: 4,
    dificultad: "media",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["cerdo", "maíz", "sal"],
    pasos: ["Freír el cerdo en trozos hasta dorar y quedar crocante.", "Preparar la masa de maíz para las arepas.", "Asar las arepas y servir junto al chicharrón."],
  },
  {
    id: 18,
    nombre: "Cuchuco de trigo con espinazo",
    categoria: "tradicional",
    tiempo: 70,
    porciones: 5,
    dificultad: "difícil",
    calorias: 550,
    dieta: "estándar",
    ingredientes: ["trigo", "espinazo de cerdo", "papa", "arveja", "cilantro"],
    pasos: ["Cocinar el espinazo hasta ablandar.", "Agregar el trigo, la papa y la arveja.", "Cocinar 30 minutos más y servir con cilantro."],
  },
  {
    id: 19,
    nombre: "Tortilla de plátano relleno",
    categoria: "tradicional",
    tiempo: 40,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["plátano maduro", "queso", "carne molida"],
    pasos: ["Cocinar el plátano y hacer un puré.", "Preparar el relleno de carne y queso.", "Formar la tortilla, rellenar y hornear 15 minutos."],
  },
  {
    id: 20,
    nombre: "Arepas rellenas de carne desmechada",
    categoria: "tradicional",
    tiempo: 45,
    porciones: 4,
    dificultad: "media",
    calorias: 480,
    dieta: "estándar",
    ingredientes: ["maíz", "carne de res", "cebolla", "tomate"],
    pasos: ["Cocinar y desmechar la carne con cebolla y tomate.", "Preparar las arepas con la masa de maíz.", "Abrir las arepas y rellenar con la carne."],
  },
  {
    id: 101,
    nombre: "Ensalada fitness de atún",
    categoria: "fitness",
    tiempo: 15,
    porciones: 2,
    dificultad: "fácil",
    calorias: 280,
    dieta: "alta en proteína",
    ingredientes: ["atún", "lechuga", "tomate", "pepino", "limón"],
    pasos: ["Picar la lechuga, el tomate y el pepino.", "Mezclar con el atún escurrido.", "Aliñar con limón y un poco de sal."],
  },
  {
    id: 102,
    nombre: "Pechuga a la plancha con vegetales",
    categoria: "fitness",
    tiempo: 25,
    porciones: 2,
    dificultad: "media",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["pechuga de pollo", "brócoli", "zanahoria", "aceite de oliva"],
    pasos: ["Sazonar la pechuga y cocinarla a la plancha.", "Cocinar el brócoli y la zanahoria al vapor.", "Servir juntos con un chorrito de aceite de oliva."],
  },
  {
    id: 103,
    nombre: "Bowl de quinua con vegetales",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "vegetariana",
    ingredientes: ["quinua", "aguacate", "tomate cherry", "espinaca", "limón"],
    pasos: ["Cocinar la quinua en agua hasta que esté suave.", "Mezclar con la espinaca, el tomate cherry y el aguacate en cubos.", "Aliñar con limón y sal al gusto."],
  },
  {
    id: 104,
    nombre: "Omelette de claras con espinaca",
    categoria: "fitness",
    tiempo: 10,
    porciones: 1,
    dificultad: "fácil",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["claras de huevo", "espinaca", "champiñones", "sal"],
    pasos: ["Batir las claras con sal.", "Sofreír la espinaca y los champiñones.", "Agregar las claras y cocinar a fuego bajo hasta cuajar."],
  },
  {
    id: 105,
    nombre: "Salmón al horno con espárragos",
    categoria: "fitness",
    tiempo: 30,
    porciones: 2,
    dificultad: "media",
    calorias: 420,
    dieta: "alta en proteína",
    ingredientes: ["salmón", "espárragos", "limón", "aceite de oliva"],
    pasos: ["Sazonar el salmón con limón, sal y aceite de oliva.", "Colocar junto a los espárragos en una bandeja.", "Hornear 20 minutos a 200°C."],
  },
  {
    id: 106,
    nombre: "Batido verde proteico",
    categoria: "fitness",
    tiempo: 5,
    porciones: 1,
    dificultad: "fácil",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["espinaca", "banano", "leche de almendras", "proteína en polvo"],
    pasos: ["Colocar todos los ingredientes en la licuadora.", "Licuar hasta que quede homogéneo.", "Servir frío."],
  },
  {
    id: 107,
    nombre: "Wrap fitness de pollo",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["tortilla integral", "pechuga de pollo", "lechuga", "tomate", "yogur griego"],
    pasos: ["Cocinar la pechuga a la plancha y cortarla en tiras.", "Untar la tortilla con yogur griego.", "Armar el wrap con lechuga, tomate y pollo, y enrollar."],
  },
  {
    id: 108,
    nombre: "Bowl de avena con frutas",
    categoria: "fitness",
    tiempo: 10,
    porciones: 1,
    dificultad: "fácil",
    calorias: 280,
    dieta: "alta en proteína",
    ingredientes: ["avena", "banano", "fresas", "leche descremada", "miel"],
    pasos: ["Cocinar la avena con la leche unos minutos.", "Cortar las frutas en trozos.", "Servir la avena con las frutas y un poco de miel."],
  },
  {
    id: 109,
    nombre: "Tacos fitness de lechuga con pollo",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["hojas de lechuga", "pechuga de pollo", "aguacate", "tomate"],
    pasos: ["Cocinar el pollo a la plancha y desmecharlo.", "Usar las hojas de lechuga como base del taco.", "Rellenar con pollo, aguacate y tomate."],
  },
  {
    id: 110,
    nombre: "Pescado al vapor con limón",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["filete de pescado", "limón", "cilantro", "zanahoria"],
    pasos: ["Colocar el pescado sazonado en la vaporera.", "Agregar rodajas de limón y zanahoria.", "Cocinar al vapor 15 minutos."],
  },
  {
    id: 111,
    nombre: "Ensalada de garbanzos",
    categoria: "fitness",
    tiempo: 15,
    porciones: 2,
    dificultad: "fácil",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["garbanzos cocidos", "tomate", "cebolla morada", "pepino", "limón"],
    pasos: ["Mezclar los garbanzos con las verduras picadas.", "Aliñar con limón, sal y un poco de aceite de oliva.", "Dejar reposar 10 minutos antes de servir."],
  },
  {
    id: 112,
    nombre: "Pollo al curry ligero",
    categoria: "fitness",
    tiempo: 30,
    porciones: 3,
    dificultad: "media",
    calorias: 420,
    dieta: "alta en proteína",
    ingredientes: ["pechuga de pollo", "curry en polvo", "leche de coco light", "cebolla"],
    pasos: ["Sofreír la cebolla y el curry.", "Agregar el pollo en cubos y dorar.", "Agregar la leche de coco y cocinar 15 minutos."],
  },
  {
    id: 113,
    nombre: "Tortilla de claras con vegetales",
    categoria: "fitness",
    tiempo: 15,
    porciones: 2,
    dificultad: "fácil",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["claras de huevo", "pimentón", "cebolla", "espinaca"],
    pasos: ["Picar el pimentón, la cebolla y la espinaca.", "Sofreír las verduras unos minutos.", "Agregar las claras batidas y cocinar hasta cuajar."],
  },
  {
    id: 114,
    nombre: "Ceviche fitness de camarón",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["camarón", "limón", "cebolla morada", "cilantro", "tomate"],
    pasos: ["Cocinar ligeramente el camarón en agua caliente.", "Mezclar con limón, cebolla, tomate y cilantro.", "Dejar marinar 10 minutos en la nevera antes de servir."],
  },
  {
    id: 115,
    nombre: "Bowl proteico de pavo",
    categoria: "fitness",
    tiempo: 25,
    porciones: 2,
    dificultad: "media",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["pechuga de pavo", "arroz integral", "brócoli", "zanahoria"],
    pasos: ["Cocinar el arroz integral.", "Cocinar la pechuga de pavo a la plancha en tiras.", "Armar el bowl con arroz, pavo y vegetales al vapor."],
  },
  {
    id: 116,
    nombre: "Panqueques de avena y banano",
    categoria: "fitness",
    tiempo: 15,
    porciones: 2,
    dificultad: "fácil",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["avena", "banano", "huevo", "canela"],
    pasos: ["Licuar la avena, el banano, el huevo y la canela.", "Verter pequeñas porciones en una sartén caliente.", "Cocinar hasta dorar por ambos lados."],
  },
  {
    id: 117,
    nombre: "Ensalada de espinaca con pollo",
    categoria: "fitness",
    tiempo: 20,
    porciones: 2,
    dificultad: "fácil",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["espinaca", "pechuga de pollo", "fresas", "almendras"],
    pasos: ["Cocinar la pechuga a la plancha y cortar en tiras.", "Mezclar la espinaca con las fresas en trozos.", "Agregar el pollo y las almendras encima."],
  },
  {
    id: 118,
    nombre: "Sopa fitness de lentejas",
    categoria: "fitness",
    tiempo: 35,
    porciones: 3,
    dificultad: "media",
    calorias: 420,
    dieta: "vegetariana",
    ingredientes: ["lentejas", "apio", "zanahoria", "cebolla", "caldo bajo en sodio"],
    pasos: ["Sofreír el apio, la zanahoria y la cebolla.", "Agregar las lentejas y el caldo.", "Cocinar a fuego medio 25 minutos."],
  },
  {
    id: 119,
    nombre: "Brochetas de pollo y vegetales",
    categoria: "fitness",
    tiempo: 25,
    porciones: 3,
    dificultad: "media",
    calorias: 350,
    dieta: "alta en proteína",
    ingredientes: ["pechuga de pollo", "pimentón", "cebolla", "calabacín"],
    pasos: ["Cortar el pollo y los vegetales en cubos.", "Armar las brochetas alternando pollo y vegetales.", "Cocinar a la plancha o parrilla 15 minutos."],
  },
  {
    id: 120,
    nombre: "Yogur griego con frutos rojos",
    categoria: "fitness",
    tiempo: 5,
    porciones: 1,
    dificultad: "fácil",
    calorias: 280,
    dieta: "alta en proteína",
    ingredientes: ["yogur griego", "fresas", "arándanos", "chía"],
    pasos: ["Colocar el yogur griego en un bowl.", "Agregar las fresas y los arándanos.", "Espolvorear semillas de chía por encima."],
  },
  {
    id: 201,
    nombre: "Ponqué navideño",
    categoria: "especial",
    tiempo: 60,
    porciones: 8,
    dificultad: "media",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "frutos secos"],
    pasos: ["Mezclar la mantequilla con el azúcar.", "Agregar los huevos y la harina poco a poco.", "Agregar los frutos secos y hornear 45 minutos."],
  },
  {
    id: 202,
    nombre: "Natilla navideña",
    categoria: "especial",
    tiempo: 40,
    porciones: 6,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["leche", "maizena", "panela", "canela", "coco rallado"],
    pasos: ["Disolver la maizena en un poco de leche fría.", "Calentar el resto de la leche con la panela y la canela.", "Agregar la maizena disuelta y revolver hasta espesar."],
  },
  {
    id: 203,
    nombre: "Buñuelos",
    categoria: "especial",
    tiempo: 45,
    porciones: 10,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["queso costeño", "almidón de yuca", "huevo", "azúcar"],
    pasos: ["Mezclar el queso rallado con el almidón, el huevo y el azúcar.", "Formar bolitas con la masa.", "Freír en aceite caliente hasta dorar."],
  },
  {
    id: 204,
    nombre: "Cena de San Valentín: pasta al pesto",
    categoria: "especial",
    tiempo: 25,
    porciones: 2,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["pasta", "albahaca", "piñones", "parmesano", "aceite de oliva"],
    pasos: ["Cocinar la pasta en agua con sal.", "Licuar la albahaca con piñones, parmesano y aceite de oliva.", "Mezclar la pasta con la salsa de pesto."],
  },
  {
    id: 205,
    nombre: "Torta de cumpleaños de chocolate",
    categoria: "especial",
    tiempo: 70,
    porciones: 10,
    dificultad: "difícil",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["harina", "cacao en polvo", "huevos", "azúcar", "chocolate para cubrir"],
    pasos: ["Mezclar los ingredientes secos y los húmedos por separado, luego unir.", "Hornear la mezcla 35 minutos a 180°C.", "Dejar enfriar y cubrir con chocolate derretido."],
  },
  {
    id: 206,
    nombre: "Pavo relleno navideño",
    categoria: "especial",
    tiempo: 150,
    porciones: 10,
    dificultad: "difícil",
    calorias: 500,
    dieta: "estándar",
    ingredientes: ["pavo", "pan", "ciruelas pasas", "tocineta", "hierbas"],
    pasos: ["Preparar el relleno con pan, ciruelas, tocineta y hierbas.", "Rellenar el pavo y sazonar por fuera.", "Hornear a temperatura baja durante 2 horas aproximadamente."],
  },
  {
    id: 207,
    nombre: "Roscón de Reyes",
    categoria: "especial",
    tiempo: 90,
    porciones: 8,
    dificultad: "difícil",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["harina", "levadura", "mantequilla", "azúcar", "fruta confitada"],
    pasos: ["Preparar la masa con harina, levadura, mantequilla y azúcar.", "Dejar reposar hasta que doble su tamaño.", "Formar el roscón, decorar con fruta confitada y hornear 25 minutos."],
  },
  {
    id: 208,
    nombre: "Cena de Acción de Gracias: puré y salsa de arándanos",
    categoria: "especial",
    tiempo: 50,
    porciones: 6,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["papa", "mantequilla", "leche", "arándanos", "azúcar"],
    pasos: ["Cocinar la papa y hacer un puré con mantequilla y leche.", "Cocinar los arándanos con azúcar hasta hacer una salsa espesa.", "Servir el puré junto con la salsa de arándanos."],
  },
  {
    id: 209,
    nombre: "Torta de bodas sencilla",
    categoria: "especial",
    tiempo: 90,
    porciones: 12,
    dificultad: "difícil",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "fondant"],
    pasos: ["Preparar el bizcocho base y hornear en varios moldes.", "Rellenar y apilar los pisos del bizcocho.", "Cubrir con fondant y decorar al gusto."],
  },
  {
    id: 210,
    nombre: "Cóctel de camarones para celebraciones",
    categoria: "especial",
    tiempo: 20,
    porciones: 4,
    dificultad: "fácil",
    calorias: 500,
    dieta: "estándar",
    ingredientes: ["camarón", "salsa de tomate", "limón", "cilantro", "aguacate"],
    pasos: ["Cocinar los camarones en agua con sal.", "Mezclar la salsa de tomate con limón y cilantro.", "Servir los camarones bañados en la salsa con aguacate."],
  },
  {
    id: 211,
    nombre: "Pan de pascua",
    categoria: "especial",
    tiempo: 80,
    porciones: 8,
    dificultad: "difícil",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["harina", "frutos secos", "frutas confitadas", "huevo", "levadura"],
    pasos: ["Preparar la masa con harina, levadura y huevo.", "Agregar los frutos secos y las frutas confitadas.", "Dejar leudar y hornear 40 minutos."],
  },
  {
    id: 212,
    nombre: "Torta de quince años",
    categoria: "especial",
    tiempo: 90,
    porciones: 15,
    dificultad: "difícil",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "crema chantilly"],
    pasos: ["Preparar y hornear el bizcocho en capas.", "Rellenar las capas con crema chantilly.", "Decorar por fuera al gusto para la celebración."],
  },
  {
    id: 213,
    nombre: "Cena romántica de risotto",
    categoria: "especial",
    tiempo: 35,
    porciones: 2,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["arroz arborio", "vino blanco", "parmesano", "caldo de verduras", "mantequilla"],
    pasos: ["Sofreír el arroz y agregar el vino blanco.", "Agregar el caldo poco a poco sin dejar de revolver.", "Al final agregar mantequilla y parmesano para dar cremosidad."],
  },
  {
    id: 214,
    nombre: "Galletas de Navidad decoradas",
    categoria: "especial",
    tiempo: 30,
    porciones: 20,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["harina", "mantequilla", "azúcar", "huevo", "glaseado"],
    pasos: ["Preparar la masa y dejar enfriar 30 minutos.", "Cortar las galletas con moldes navideños y hornear 12 minutos.", "Decorar con glaseado una vez frías."],
  },
  {
    id: 215,
    nombre: "Torta de Halloween de calabaza",
    categoria: "especial",
    tiempo: 60,
    porciones: 8,
    dificultad: "media",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["puré de calabaza", "harina", "huevos", "azúcar", "canela"],
    pasos: ["Mezclar el puré de calabaza con los huevos y el azúcar.", "Agregar la harina y la canela poco a poco.", "Hornear 40 minutos a 180°C."],
  },
  {
    id: 216,
    nombre: "Cena de fin de año: lomo al horno",
    categoria: "especial",
    tiempo: 100,
    porciones: 6,
    dificultad: "difícil",
    calorias: 500,
    dieta: "estándar",
    ingredientes: ["lomo de cerdo", "miel", "mostaza", "romero", "papas"],
    pasos: ["Untar el lomo con una mezcla de miel, mostaza y romero.", "Colocar junto a las papas en una bandeja.", "Hornear a 180°C durante 1 hora y media."],
  },
  {
    id: 217,
    nombre: "Cupcakes de cumpleaños",
    categoria: "especial",
    tiempo: 35,
    porciones: 12,
    dificultad: "media",
    calorias: 450,
    dieta: "estándar",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "chispas de colores"],
    pasos: ["Preparar la mezcla de bizcocho como para una torta normal.", "Repartir en moldes individuales de cupcake.", "Hornear 20 minutos y decorar con chispas de colores."],
  },
  {
    id: 218,
    nombre: "Ponche navideño de frutas",
    categoria: "especial",
    tiempo: 30,
    porciones: 8,
    dificultad: "media",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["frutas variadas", "jugo de naranja", "canela", "clavos de olor"],
    pasos: ["Picar las frutas en trozos pequeños.", "Calentar el jugo de naranja con canela y clavos.", "Agregar las frutas y servir caliente."],
  },
  {
    id: 219,
    nombre: "Cena de Nochevieja: uvas y brindis de honor",
    categoria: "especial",
    tiempo: 15,
    porciones: 8,
    dificultad: "fácil",
    calorias: 500,
    dieta: "vegetariana",
    ingredientes: ["uvas verdes", "jugo de uva o espumante sin alcohol", "hielo"],
    pasos: ["Preparar una copa con 12 uvas por persona para la tradición de medianoche.", "Servir el jugo de uva o espumante bien frío.", "Brindar en familia al iniciar el nuevo año."],
  },
  {
    id: 220,
    nombre: "Torta de graduación",
    categoria: "especial",
    tiempo: 90,
    porciones: 12,
    dificultad: "difícil",
    calorias: 450,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "fondant o merengue"],
    pasos: ["Hornear el bizcocho base en capas.", "Rellenar y armar la torta.", "Decorar con fondant o merengue y un mensaje de felicitación."],
  },
];

export default recetas;