// Recetas del proyecto Charin Cook — enfocado en POSTRES.
// 3 categorías: tradicional (postres clásicos), fitness (postres saludables),
// especial (postres para fechas especiales). Para agregar un postre nuevo,
// copia un bloque { ... } con un id único.

const recetas = [
  {
    id: 1,
    nombre: "Arroz con leche",
    categoria: "tradicional",
    tiempo: 40,
    porciones: 6,
    dificultad: "media",
    calorias: 320,
    dieta: "vegetariana",
    ingredientes: ["arroz", "leche", "canela", "clavos de olor", "panela"],
    pasos: ["Cocina el arroz en agua hasta que esté suave.", "Agrega la leche, la canela y los clavos, y cocina a fuego bajo 20 minutos revolviendo.", "Endulza con panela raspada y sigue cocinando hasta que espese.", "Retira la canela y los clavos, y deja enfriar antes de servir."],
  },
  {
    id: 2,
    nombre: "Cocadas",
    categoria: "tradicional",
    tiempo: 35,
    porciones: 10,
    dificultad: "fácil",
    calorias: 210,
    dieta: "vegetariana",
    ingredientes: ["coco rallado", "leche condensada", "azúcar", "clavos de olor"],
    pasos: ["Mezcla el coco rallado con la leche condensada y el azúcar en una olla.", "Cocina a fuego medio, revolviendo constantemente, hasta que espese.", "Forma pequeñas bolitas o montoncitos sobre una bandeja engrasada.", "Deja enfriar hasta que endurezcan un poco antes de servir."],
  },
  {
    id: 3,
    nombre: "Brevas con arequipe",
    categoria: "tradicional",
    tiempo: 25,
    porciones: 4,
    dificultad: "fácil",
    calorias: 250,
    dieta: "vegetariana",
    ingredientes: ["brevas", "arequipe", "queso campesino"],
    pasos: ["Cocina las brevas en agua con panela hasta que estén blandas y dulces.", "Abre cada breva por la mitad sin separarla del todo.", "Rellena con arequipe y un trozo de queso campesino.", "Sirve tibias o frías, al gusto."],
  },
  {
    id: 4,
    nombre: "Torta de plátano maduro",
    categoria: "tradicional",
    tiempo: 50,
    porciones: 8,
    dificultad: "media",
    calorias: 300,
    dieta: "vegetariana",
    ingredientes: ["plátano maduro", "harina", "huevos", "azúcar", "canela"],
    pasos: ["Licúa el plátano maduro con los huevos y el azúcar.", "Agrega la harina y la canela poco a poco, mezclando bien.", "Vierte en un molde engrasado y hornea 35 minutos a 180°C.", "Deja enfriar antes de desmoldar y servir."],
  },
  {
    id: 5,
    nombre: "Mazamorra",
    categoria: "tradicional",
    tiempo: 45,
    porciones: 6,
    dificultad: "media",
    calorias: 280,
    dieta: "vegetariana",
    ingredientes: ["maíz trillado", "leche", "panela", "canela"],
    pasos: ["Remoja el maíz trillado varias horas y luego cocínalo hasta que esté blando.", "Agrega la leche y la panela raspada, revolviendo bien.", "Cocina a fuego bajo hasta que tome una consistencia espesa.", "Sirve fría o tibia, con canela al gusto."],
  },
  {
    id: 6,
    nombre: "Bocadillo con queso",
    categoria: "tradicional",
    tiempo: 10,
    porciones: 2,
    dificultad: "fácil",
    calorias: 260,
    dieta: "vegetariana",
    ingredientes: ["bocadillo de guayaba", "queso campesino"],
    pasos: ["Corta el bocadillo de guayaba en trozos pequeños.", "Corta el queso campesino en tajadas del mismo tamaño.", "Sirve juntos en un plato, alternando bocadillo y queso."],
  },
  {
    id: 7,
    nombre: "Milhoja",
    categoria: "tradicional",
    tiempo: 60,
    porciones: 8,
    dificultad: "difícil",
    calorias: 350,
    dieta: "vegetariana",
    ingredientes: ["masa de hojaldre", "arequipe", "azúcar glas"],
    pasos: ["Hornea las láminas de masa de hojaldre hasta que doren y queden crocantes.", "Deja enfriar por completo las láminas horneadas.", "Arma capas alternando hojaldre y arequipe.", "Espolvorea azúcar glas por encima antes de servir."],
  },
  {
    id: 8,
    nombre: "Flan de caramelo",
    categoria: "tradicional",
    tiempo: 55,
    porciones: 6,
    dificultad: "media",
    calorias: 270,
    dieta: "vegetariana",
    ingredientes: ["huevos", "leche condensada", "leche", "azúcar"],
    pasos: ["Prepara un caramelo con azúcar derretida y cubre el fondo de un molde.", "Licúa los huevos con la leche condensada y la leche.", "Vierte la mezcla sobre el caramelo y hornea a baño María 40 minutos.", "Deja enfriar en la nevera antes de desmoldar."],
  },
  {
    id: 101,
    nombre: "Yogur griego con frutos rojos y granola",
    categoria: "fitness",
    tiempo: 5,
    porciones: 1,
    dificultad: "fácil",
    calorias: 220,
    dieta: "alta en proteína",
    ingredientes: ["yogur griego", "fresas", "arándanos", "granola"],
    pasos: ["Coloca el yogur griego en un bowl.", "Agrega las fresas y los arándanos encima.", "Espolvorea la granola justo antes de servir."],
  },
  {
    id: 102,
    nombre: "Gelatina light de frutas",
    categoria: "fitness",
    tiempo: 15,
    porciones: 4,
    dificultad: "fácil",
    calorias: 60,
    dieta: "vegetariana",
    ingredientes: ["gelatina sin azúcar", "fresas", "kiwi", "agua"],
    pasos: ["Disuelve la gelatina sin azúcar en agua caliente siguiendo las instrucciones del paquete.", "Agrega trozos de fresa y kiwi en el fondo de los moldes.", "Vierte la gelatina líquida encima y refrigera hasta que cuaje."],
  },
  {
    id: 103,
    nombre: "Mousse de aguacate y cacao",
    categoria: "fitness",
    tiempo: 15,
    porciones: 4,
    dificultad: "fácil",
    calorias: 190,
    dieta: "vegetariana",
    ingredientes: ["aguacate", "cacao en polvo", "miel", "leche de almendras"],
    pasos: ["Licúa el aguacate con el cacao, la miel y un poco de leche de almendras.", "Bate hasta lograr una textura suave y cremosa.", "Sirve en copas individuales y refrigera 20 minutos antes de servir."],
  },
  {
    id: 104,
    nombre: "Compota de manzana sin azúcar",
    categoria: "fitness",
    tiempo: 20,
    porciones: 4,
    dificultad: "fácil",
    calorias: 90,
    dieta: "vegetariana",
    ingredientes: ["manzana", "canela", "agua"],
    pasos: ["Pela y corta las manzanas en cubos.", "Cocina en agua con canela a fuego medio hasta que estén blandas.", "Tritura un poco con un tenedor para lograr una textura de compota."],
  },
  {
    id: 105,
    nombre: "Paletas de fruta natural",
    categoria: "fitness",
    tiempo: 10,
    porciones: 6,
    dificultad: "fácil",
    calorias: 70,
    dieta: "vegetariana",
    ingredientes: ["mango", "fresas", "agua", "limón"],
    pasos: ["Licúa la fruta con un poco de agua y limón.", "Vierte la mezcla en moldes de paletas.", "Congela mínimo 4 horas antes de desmoldar."],
  },
  {
    id: 106,
    nombre: "Chía pudding con mango",
    categoria: "fitness",
    tiempo: 10,
    porciones: 2,
    dificultad: "fácil",
    calorias: 180,
    dieta: "vegetariana",
    ingredientes: ["semillas de chía", "leche de almendras", "mango", "miel"],
    pasos: ["Mezcla las semillas de chía con la leche de almendras y un poco de miel.", "Deja reposar en la nevera mínimo 3 horas, revolviendo una vez a la mitad.", "Sirve con trozos de mango fresco encima."],
  },
  {
    id: 107,
    nombre: "Brownie fit de banano y avena",
    categoria: "fitness",
    tiempo: 30,
    porciones: 8,
    dificultad: "media",
    calorias: 210,
    dieta: "vegetariana",
    ingredientes: ["banano", "avena", "cacao en polvo", "huevo"],
    pasos: ["Licúa el banano maduro con el huevo.", "Agrega la avena y el cacao en polvo, mezclando bien.", "Vierte en un molde pequeño y hornea 20 minutos a 180°C.", "Deja enfriar antes de cortar en cuadros."],
  },
  {
    id: 108,
    nombre: "Ensalada de frutas con menta",
    categoria: "fitness",
    tiempo: 15,
    porciones: 4,
    dificultad: "fácil",
    calorias: 110,
    dieta: "vegetariana",
    ingredientes: ["manzana", "piña", "uvas", "menta", "limón"],
    pasos: ["Corta todas las frutas en trozos pequeños.", "Mezcla en un bowl grande con jugo de limón.", "Agrega hojas de menta picada antes de servir bien frío."],
  },
  {
    id: 201,
    nombre: "Natilla navideña",
    categoria: "especial",
    tiempo: 40,
    porciones: 6,
    dificultad: "media",
    calorias: 300,
    dieta: "vegetariana",
    ingredientes: ["leche", "maizena", "panela", "canela", "coco rallado"],
    pasos: ["Disuelve la maizena en un poco de leche fría.", "Calienta el resto de la leche con la panela y la canela.", "Agrega la maizena disuelta y revuelve hasta que espese.", "Vierte en un molde, espolvorea coco rallado y deja enfriar."],
  },
  {
    id: 202,
    nombre: "Buñuelos",
    categoria: "especial",
    tiempo: 45,
    porciones: 10,
    dificultad: "media",
    calorias: 260,
    dieta: "vegetariana",
    ingredientes: ["queso costeño", "almidón de yuca", "huevo", "azúcar"],
    pasos: ["Mezcla el queso rallado con el almidón, el huevo y el azúcar.", "Forma bolitas con la masa.", "Fríe en aceite caliente hasta que doren y crezcan.", "Sirve tibios."],
  },
  {
    id: 203,
    nombre: "Roscón de Reyes",
    categoria: "especial",
    tiempo: 90,
    porciones: 8,
    dificultad: "difícil",
    calorias: 310,
    dieta: "vegetariana",
    ingredientes: ["harina", "levadura", "mantequilla", "azúcar", "fruta confitada"],
    pasos: ["Prepara la masa con harina, levadura, mantequilla y azúcar.", "Deja reposar hasta que doble su tamaño.", "Forma el roscón, decora con fruta confitada y hornea 25 minutos."],
  },
  {
    id: 204,
    nombre: "Torta de cumpleaños de chocolate",
    categoria: "especial",
    tiempo: 70,
    porciones: 10,
    dificultad: "difícil",
    calorias: 340,
    dieta: "vegetariana",
    ingredientes: ["harina", "cacao en polvo", "huevos", "azúcar", "chocolate para cubrir"],
    pasos: ["Mezcla los ingredientes secos y los húmedos por separado, luego únelos.", "Hornea la mezcla 35 minutos a 180°C.", "Deja enfriar por completo.", "Cubre con chocolate derretido antes de servir."],
  },
  {
    id: 205,
    nombre: "Galletas de Navidad decoradas",
    categoria: "especial",
    tiempo: 30,
    porciones: 20,
    dificultad: "media",
    calorias: 180,
    dieta: "vegetariana",
    ingredientes: ["harina", "mantequilla", "azúcar", "huevo", "glaseado"],
    pasos: ["Prepara la masa y refrigérala 30 minutos.", "Corta las galletas con moldes navideños y hornea 12 minutos.", "Deja enfriar por completo y decora con el glaseado."],
  },
  {
    id: 206,
    nombre: "Cupcakes para San Valentín",
    categoria: "especial",
    tiempo: 35,
    porciones: 12,
    dificultad: "media",
    calorias: 260,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "chispas de colores"],
    pasos: ["Prepara la mezcla de bizcocho batiendo mantequilla, azúcar y huevos.", "Agrega la harina poco a poco y mezcla bien.", "Reparte en capacillos y hornea 20 minutos.", "Decora con chispas de colores al enfriar."],
  },
  {
    id: 207,
    nombre: "Pan de pascua",
    categoria: "especial",
    tiempo: 80,
    porciones: 8,
    dificultad: "difícil",
    calorias: 320,
    dieta: "vegetariana",
    ingredientes: ["harina", "frutos secos", "frutas confitadas", "huevo", "levadura"],
    pasos: ["Prepara la masa con harina, levadura y huevo.", "Agrega los frutos secos y las frutas confitadas.", "Deja leudar y hornea 40 minutos a 180°C."],
  },
  {
    id: 208,
    nombre: "Torta de graduación",
    categoria: "especial",
    tiempo: 90,
    porciones: 12,
    dificultad: "difícil",
    calorias: 330,
    dieta: "vegetariana",
    ingredientes: ["harina", "huevos", "azúcar", "mantequilla", "fondant o merengue"],
    pasos: ["Hornea el bizcocho base en capas.", "Deja enfriar y rellena entre capas.", "Decora por fuera con fondant o merengue para la ocasión."],
  },
];

export default recetas;